language: python
python: 
        - 3.7
services:
        - mysql
env:
        - DJANGO=2.2.3 DB=mysql
install: pip install -r requirements/development.txt
before_script:
        - mysql -e 'create database voldb;' -u root
script: 
        - python3 manage.py test --settings=voldb.settings.development
