language: python
python: 
        - 3.7
        - 3.6
services:
        - mysql
env:
        - DJANGO=2.2.3 DB=mysql
install: pip install -r requirements/base.txt
before_script:
        - mysql -e 'create database test;' -u root
script: 
        - python3 manage.py makemigrations vol --settings=voldb.settings.development
        - python3 manage.py migrate --settings=voldb.settings.development
        - python3 manage.py test --settings=voldb.settings.development
