"""
Django settings for voldb project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

from .base import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['127.0.0.1', '0.0.0.0', 'localhost']
INTERNAL_IPS = ('10.0.2.2', '127.0.0.1')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            # Debian
            'read_default_file': '/etc/mysql/conf.d/mysql.cnf',
        }
    }
}

INSTALLED_APPS = [
    'debug_toolbar',
    'bootstrap_modal_forms',
] + INSTALLED_APPS

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
] + MIDDLEWARE

STATIC_ROOT = os.path.join(BASE_DIR, "static")