# Generated by Django 2.1.3 on 2018-12-03 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeAita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_aita', models.CharField(max_length=5, verbose_name='Code Aita')),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(max_length=10, verbose_name='Fonction')),
            ],
        ),
        migrations.CreateModel(
            name='Immatriculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=10, verbose_name="Immatriculation de l'avion")),
            ],
        ),
        migrations.CreateModel(
            name='Pilote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=255, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de famille')),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste_nom', models.CharField(max_length=255, verbose_name='Nom du poste')),
                ('poste_abbr', models.CharField(max_length=10, verbose_name='Abbréviation')),
            ],
        ),
        migrations.CreateModel(
            name='TypeAvion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_avion', models.CharField(max_length=255, verbose_name="Type d'avion")),
                ('nb_moteurs', models.IntegerField(verbose_name='Nombre de moteurs')),
            ],
        ),
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date du vol')),
                ('duree_jour', models.DurationField(verbose_name='Durée de vol de jour')),
                ('duree_nuit', models.DurationField(verbose_name='Durée de vol de nuit')),
                ('arrivee_ifr', models.BooleanField(verbose_name='Arrivée IFR ?')),
                ('observation', models.TextField(verbose_name='Observations')),
                ('simu', models.BooleanField(verbose_name='Simulateur ?')),
                ('arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vol_arrivee', to='vol.CodeAita', verbose_name="Code AITA de l'aéroport d'arrivée'")),
                ('cdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vol_cdb', to='vol.Pilote', verbose_name='Commandant de bord')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vol_depart', to='vol.CodeAita', verbose_name="Code AITA de l'aéroport de départ")),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vol_fonction', to='vol.Fonction', verbose_name='Fonction à bord')),
                ('immatriculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vol_immatriculation', to='vol.Immatriculation', verbose_name="Immatriculation de l'avion")),
                ('instructeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vol_instructeur', to='vol.Pilote', verbose_name='Instructeur')),
                ('obs1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vol_obs1', to='vol.Pilote', verbose_name='Observateur 1')),
                ('obs2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vol_obs2', to='vol.Pilote', verbose_name='Observateur 2')),
                ('opl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vol_opl', to='vol.Pilote', verbose_name='Copilote')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vol_poste', to='vol.Poste', verbose_name='Poste')),
            ],
        ),
        migrations.AddField(
            model_name='immatriculation',
            name='type_avion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vol.TypeAvion'),
        ),
    ]
