# Generated by Django 2.1.3 on 2018-12-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeavion',
            name='nb_moteurs',
            field=models.CharField(choices=[('1', 'Monomoteur'), ('2', 'Multimoteurs')], max_length=25, verbose_name='Nombre de moteurs'),
        ),
    ]
