# Generated by Django 2.1.3 on 2018-12-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0002_auto_20181203_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonction',
            name='fonction',
            field=models.CharField(choices=[('PF', 'PF'), ('PNF', 'PNF'), ('MIX', 'MIX')], max_length=10, verbose_name='Fonction'),
        ),
    ]
