# Generated by Django 2.1.3 on 2018-12-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0003_auto_20181203_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vol',
            name='fonction',
            field=models.CharField(choices=[('PF', 'PF'), ('PNF', 'PNF'), ('MIX', 'MIX')], max_length=3, verbose_name='Fonction'),
        ),
    ]
