# Generated by Django 2.1.3 on 2018-12-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0004_auto_20181203_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fonction',
        ),
    ]
