# Generated by Django 2.1.3 on 2018-12-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0006_auto_20181203_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vol',
            name='fonction',
            field=models.CharField(choices=[('PF', 'PF'), ('PNF', 'PNF'), ('MIX', 'MIX')], max_length=3, verbose_name='Fonction occupée'),
        ),
        migrations.AlterField(
            model_name='vol',
            name='poste',
            field=models.CharField(choices=[('CDB', 'Commandant de bord'), ('OPL', 'Copilote'), ('Instruct', 'Instructeur'), ('OBS', 'Observateur')], max_length=20, verbose_name='Poste occupé'),
        ),
    ]
