# Generated by Django 2.1.3 on 2018-12-03 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0007_auto_20181203_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vol',
            name='instructeur',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vol_instructeur', to='vol.Pilote', verbose_name='Instructeur'),
        ),
        migrations.AlterField(
            model_name='vol',
            name='obs1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vol_obs1', to='vol.Pilote', verbose_name='Observateur 1'),
        ),
        migrations.AlterField(
            model_name='vol',
            name='obs2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vol_obs2', to='vol.Pilote', verbose_name='Observateur 2'),
        ),
    ]
