# Generated by Django 2.1.3 on 2018-12-03 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0009_auto_20181203_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vol',
            name='arrivee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vol_arrivee', to='vol.CodeAita', verbose_name="Code AITA de l'aéroport d'arrivée"),
        ),
    ]
