# Generated by Django 2.1.3 on 2018-12-03 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0010_auto_20181203_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vol',
            name='instructeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vol_instructeur', to='vol.Pilote', verbose_name='Instructeur'),
        ),
    ]
