# Generated by Django 2.1.3 on 2018-12-03 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0012_auto_20181203_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vol',
            name='arrivee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vol_arrivee', to='vol.CodeAita', verbose_name='Arrivée'),
        ),
        migrations.AlterField(
            model_name='vol',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vol_depart', to='vol.CodeAita', verbose_name='Départ'),
        ),
    ]
