# Generated by Django 2.1.3 on 2018-12-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0014_codeaita_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeaita',
            name='ville',
            field=models.CharField(max_length=50, verbose_name='Ville'),
        ),
    ]
