# Generated by Django 2.1.3 on 2018-12-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0015_auto_20181203_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeaita',
            name='ville',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ville'),
        ),
    ]
