# Generated by Django 2.1.3 on 2018-12-03 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0016_auto_20181203_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immatriculation',
            name='type_avion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vol.TypeAvion'),
        ),
        migrations.AlterField(
            model_name='vol',
            name='arrivee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vol_arrivee', to='vol.CodeAita', verbose_name='Arrivée'),
        ),
        migrations.AlterField(
            model_name='vol',
            name='cdb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vol_cdb', to='vol.Pilote', verbose_name='Commandant de bord'),
        ),
        migrations.AlterField(
            model_name='vol',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vol_depart', to='vol.CodeAita', verbose_name='Départ'),
        ),
        migrations.AlterField(
            model_name='vol',
            name='immatriculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vol_immatriculation', to='vol.Immatriculation', verbose_name="Immatriculation de l'avion"),
        ),
        migrations.AlterField(
            model_name='vol',
            name='instructeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vol_instructeur', to='vol.Pilote', verbose_name='Instructeur'),
        ),
        migrations.AlterField(
            model_name='vol',
            name='obs1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vol_obs1', to='vol.Pilote', verbose_name='Observateur 1'),
        ),
        migrations.AlterField(
            model_name='vol',
            name='obs2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vol_obs2', to='vol.Pilote', verbose_name='Observateur 2'),
        ),
        migrations.AlterField(
            model_name='vol',
            name='opl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vol_opl', to='vol.Pilote', verbose_name='Copilote'),
        ),
    ]
